import { iconNames } from "lucide-react/dynamic";

export const ALL_ICON_NAMES: readonly string[] = iconNames;

const ALL_ICON_NAME_SET = new Set(ALL_ICON_NAMES);

export function isValidIconName(name: string): boolean {
  return ALL_ICON_NAME_SET.has(name);
}

export function humanizeIconName(name: string): string {
  return name
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

// A curated starting point shown before the user searches — biased toward
// things people actually inventory at home or in a small org. All names are
// verified against lucide-react's real icon set.
export const POPULAR_ICON_NAMES: string[] = [
  "laptop",
  "monitor",
  "printer",
  "camera",
  "webcam",
  "tv",
  "speaker",
  "headphones",
  "mic",
  "gamepad-2",
  "joystick",
  "smartphone",
  "tablet",
  "watch",
  "hard-drive",
  "server",
  "router",
  "wifi",
  "cpu",
  "memory-stick",
  "battery",
  "battery-charging",
  "plug",
  "plug-zap",
  "usb",
  "cable",
  "mouse",
  "keyboard",
  "projector",
  "disc-3",
  "video",
  "image",
  "book",
  "car",
  "truck",
  "bike",
  "ship",
  "plane",
  "train",
  "forklift",
  "drone",
  "wrench",
  "hammer",
  "drill",
  "ruler",
  "toolbox",
  "cog",
  "power",
  "flashlight",
  "fan",
  "thermometer",
  "lamp",
  "armchair",
  "sofa",
  "bed",
  "bed-double",
  "refrigerator",
  "washing-machine",
  "microwave",
  "coffee",
  "utensils",
  "scissors",
  "paintbrush",
  "guitar",
  "piano",
  "dumbbell",
  "tent",
  "umbrella",
  "backpack",
  "luggage",
  "shirt",
  "briefcase",
  "box",
  "package",
  "boxes",
  "archive",
  "container",
  "warehouse",
  "building",
  "building-2",
  "home",
  "key",
  "lock",
  "shield",
  "credit-card",
  "wallet",
  "gem",
  "shopping-bag",
  "shopping-cart",
  "folder",
  "file",
  "clipboard",
  "tag",
  "tags",
  "puzzle",
  "anchor",
  "sailboat",
  "rocket",
  "satellite-dish",
  "antenna",
  "leaf",
  "tree-pine",
  "paw-print",
  "fish",
  "dog",
  "cat",
  "baby",
  "user",
  "users",
];
