import { CABLE_FIELD_SCHEMA } from "@/lib/asset-fields";
import type { ExportBundle } from "@/lib/data-io/types";

// A small, self-contained example — illustrates locations with nesting,
// a built-in type (Cable), a custom type with its own fields (Laptop),
// tags, a parent/child relationship, a kit, and a couple of consumables
// (one with a location and low-stock threshold, one without). Not queried
// from any real data, so it's safe to hand out as a downloadable template.
export const EXAMPLE_BUNDLE: ExportBundle = {
  meta: { version: 1 },
  locations: [
    { path: "Home", notes: null },
    { path: "Home / Office", notes: "Desk and shelving unit" },
    { path: "Home / Garage", notes: null },
  ],
  assetTypes: [
    { name: "Cable", category: "Cables", icon: null, fieldSchema: [...CABLE_FIELD_SCHEMA] },
    { name: "Generic", category: "Uncategorized", icon: null, fieldSchema: [] },
    {
      name: "Laptop",
      category: "Electronics",
      icon: null,
      fieldSchema: [
        { key: "brand", label: "Brand", type: "TEXT", required: true },
        { key: "model", label: "Model", type: "TEXT" },
        { key: "ramGb", label: "RAM (GB)", type: "NUMBER" },
      ],
    },
  ],
  assets: [
    {
      assetTag: "AM-EXAMPLE001",
      name: "Dell XPS 13",
      assetType: "Laptop",
      location: "Home / Office",
      assignedToEmail: null,
      parentAssetTag: null,
      status: "IN_USE",
      notes: "Primary work laptop",
      purchaseDate: "2024-03-15",
      purchasePrice: "1299.00",
      purchaseCurrency: "EUR",
      vendor: "Dell",
      warrantyExpiresAt: "2027-03-15",
      tags: ["work", "laptop"],
      customFields: { brand: "Dell", model: "XPS 13", ramGb: 16 },
    },
    {
      assetTag: "AM-EXAMPLE002",
      name: "USB-C to HDMI Cable",
      assetType: "Cable",
      location: "Home / Office",
      assignedToEmail: null,
      parentAssetTag: null,
      status: "IN_STORAGE",
      notes: null,
      purchaseDate: "2024-06-01",
      purchasePrice: "12.50",
      purchaseCurrency: "EUR",
      vendor: null,
      warrantyExpiresAt: null,
      tags: ["usb-c", "hdmi"],
      customFields: {
        category: "USB",
        connectorA: "USB-C",
        connectorB: "HDMI",
        protocols: ["USB4"],
        length: { value: 1.8, unit: "m" },
      },
    },
    {
      assetTag: "AM-EXAMPLE003",
      name: "Raspberry Pi 4 (Unit A)",
      assetType: "Generic",
      location: "Home / Garage",
      assignedToEmail: null,
      parentAssetTag: null,
      status: "IN_STORAGE",
      notes: "First of three identical units",
      purchaseDate: null,
      purchasePrice: null,
      purchaseCurrency: null,
      vendor: null,
      warrantyExpiresAt: null,
      tags: ["raspberry-pi"],
      customFields: {},
    },
    {
      assetTag: "AM-EXAMPLE004",
      name: "256GB NVMe SSD",
      assetType: "Generic",
      location: "Home / Office",
      assignedToEmail: null,
      parentAssetTag: "AM-EXAMPLE001", // installed inside the Dell XPS 13
      status: "IN_USE",
      notes: null,
      purchaseDate: null,
      purchasePrice: null,
      purchaseCurrency: null,
      vendor: null,
      warrantyExpiresAt: null,
      tags: [],
      customFields: {},
    },
  ],
  kits: [
    {
      name: "Travel Kit",
      description: "Grab-and-go bag for work trips",
      memberAssetTags: ["AM-EXAMPLE001", "AM-EXAMPLE002"],
    },
  ],
  consumables: [
    {
      name: "Hand soap",
      category: "Cleaning supplies",
      quantity: 4,
      lowStockThreshold: 2,
      location: "Home / Office",
    },
    {
      name: "Address labels",
      category: "Office supplies",
      quantity: 1,
      lowStockThreshold: null,
      location: null,
    },
  ],
};
